apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: student-deployment 
  labels: 
    app: student 
spec: 
  replicas: 2
  strategy:
    type: RollingUpdate 
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 0
  selector: 
    matchLabels:  
      app: student 
  template: 
    metadata: 
      labels: 
        app: student 
    spec: 
      containers: 
        - name: student-container
          image: 554663574879.dkr.ecr.ap-south-1.amazonaws.com/student:5134e162c014129eb9a3533a748e1d236a4f0b43
          ports: 
            - containerPort: 8080
          imagePullPolicy: Always
        
          resources: 
            requests: 
              cpu: "200m"
              memory: "100Mi"
            limits:    
              cpu: "400m"
              memory: "200Mi"
