apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: student-deployment 
  labels: 
    app: student 
spec: 
  replicas: 4
  strategy:
    type: RollingUpdate 
    rollingUpdate: 
      maxSurge: 2
      maxUnavailable: 2
  selector: 
    matchLabels:  
      app: student 
  template: 
    metadata: 
      labels: 
        app: student 
    spec: 
      containers: 
        - name: student-container
          image: 554663574879.dkr.ecr.ap-south-1.amazonaws.com/student:687ae0e50f084a96baa2f2f0a477d545e7116dec
          ports: 
            - containerPort: 8080
          imagePullPolicy: Always
        
          resources: 
            requests: 
              cpu: "200m"
              memory: "100Mi"
            limits:    
              cpu: "400m"
              memory: "200Mi"
